language: elixir

cache:
  directories:
    - deps
services:
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=place_your_account_name_here
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
before_install:
script:
  # Install dependencies if Travis won't do it by default
  # - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
